# Generated by Django 3.1.2 on 2020-10-13 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='regulatory__license_f961df_idx',
        ),
    ]
