# Generated by Django 3.1.2 on 2020-10-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelevantDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='文件名称')),
                ('file', models.FileField(upload_to='document', verbose_name='相关文件')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.DeleteModel(
            name='CustomerFile',
        ),
        migrations.DeleteModel(
            name='FlowDetailFile',
        ),
        migrations.DeleteModel(
            name='FlowFile',
        ),
    ]
