# Generated by Django 3.1.2 on 2020-10-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0002_auto_20201006_0343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='展示名称')),
                ('content', models.TextField(verbose_name='展示内容')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='relevantdocument',
            options={'ordering': ('id',), 'verbose_name': '相关文件', 'verbose_name_plural': '相关文件'},
        ),
    ]
