# Generated by Django 3.1.2 on 2020-10-11 05:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0004_auto_20201006_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='展示内容'),
        ),
    ]
